[project]
org-name= "ballerina"
version= "0.1.0"

[dependencies]
"ballerina/auth" = "1.0.1"
"ballerina/cache" = "2.0.1"
"ballerina/config" = "1.0.1"
"ballerina/crypto" = "1.0.1"
"ballerina/file" = "0.5.2"
"ballerina/http" = "1.0.0"
"ballerina/io" = "0.5.1"
"ballerina/log" = "1.0.1"
"ballerina/mime" = "1.0.1"
"ballerina/runtime" = "0.5.1"
"ballerina/reflect" = "0.5.1"
"ballerina/stringutils" = "0.5.1"
"ballerina/system" = "0.6.1"
"ballerina/time" = "1.0.2"
"ballerina/task" = "1.1.1"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "graphql"
    version = "0.1.0-SNAPSHOT"
    path = "../graphql-native/build/libs/graphql-native-0.1.0-SNAPSHOT.jar"
    groupId = "org.ballerinalang.stdlib.graphql"
    modules = ["graphql"]
