[package]
org = "ballerina"
name = "graphql"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../graphql-native/build/libs/graphql-native-@project.version@.jar"
groupId = "io.ballerina.stdlib.graphql"
artifactId = "graphql"
version = "@project.version@"
modules = ["graphql"]
