[plugin]
id = "graphql-compiler-plugin"
class = "io.ballerina.stdlib.graphql.compiler.GraphqlCompilerPlugin"

[[dependency]]
path = "../graphql-compiler-plugin/build/libs/graphql-compiler-plugin-0.2.0-alpha9-SNAPSHOT.jar"
