[package]
org = "ballerina"
name = "graphql"
version = "1.14.1"
authors = ["Ballerina"]
export=["graphql", "graphql.subgraph", "graphql.dataloader"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241025-103700-5c9e6a27"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-native"
version = "1.14.1"
path = "../native/build/libs/graphql-native-1.14.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-commons"
version = "1.14.1"
path = "../commons/build/libs/graphql-commons-1.14.1-SNAPSHOT.jar"
