[package]
org = "ballerina"
name = "graphql"
version = "1.15.1"
authors = ["Ballerina"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[[package.modules]]
name = "graphql.dataloader"
description="This module provides a way to load data from a data source with batching and caching capabilities."
export=true

[[package.modules]]
name = "graphql.subgraph"
description="This module provides a way to create a subgraphs for a federated GraphQL service"
export=true

[[package.modules]]
name = "graphql.parser"
description="The GraphQL document parser module"
export=false

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-native"
version = "1.15.1"
path = "../native/build/libs/graphql-native-1.15.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-commons"
version = "1.15.1"
path = "../commons/build/libs/graphql-commons-1.15.1-SNAPSHOT.jar"
