[plugin]
id = "graphql-compiler-plugin"
class = "io.ballerina.stdlib.graphql.compiler.GraphqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/graphql-compiler-plugin-1.5.1-SNAPSHOT.jar"

[[dependency]]
path = "../commons/build/libs/graphql-commons-1.5.1-SNAPSHOT.jar"
