name: Build

on:
    push:
        branches:
            - master
        paths-ignore:
            - '*.md'
            - 'docs/**'
            - 'load-tests/**'

    workflow_dispatch:

jobs:
    call_workflow:
        name: Run Build Workflow
        if: ${{ github.repository_owner == 'ballerina-platform' }}
        uses: ballerina-platform/ballerina-standard-library/.github/workflows/build-timestamp-master-template.yml@main
        with:
            ballerina-bot-username: ${{ secrets.BALLERINA_BOT_USERNAME }}
            ballerina-bot-token: ${{ secrets.BALLERINA_BOT_TOKEN }}
